matrix:
  fast_finish: true
  include:
    - language: csharp
      script:
        - docker create --tty --interactive --name bridgec bridgedotnet/bridge
        - docker start bridgec
        - docker container exec bridgec bridge new
        - docker container exec bridgec bridge build
      
    - language: csharp
      script:
        - msbuild "./Grekum.sln"
