matrix:
  include:
    - language: node_js
      sudo: true
      node_js:
        - "node"
      install:
        - npm install
      script:
        - npm test

    - language: csharp
      script:
        - bridge build
