matrix:
  fast_finish: true
  include:
    - language: node_js
      sudo: true
      node_js:
        - "node"
      install:
        - npm install
      script:
        - npm test

    - language: csharp
      script:
        - docker create --tty --interactive --name bridgec bridgedotnet/bridge
        - docker start bridgec
        - docker container exec bridgec bridge build
      
    - language: csharp
      script:
        - cd original
        - msbuild Greekum.sln
