matrix:
  include:
    - language: node_js
      sudo: true
      node_js:
        - "7"
      install:
        - npm install
      script:
        - npm test

    - language: csharp
      script:
        - docker create --tty --i --name bridgec bridgedotnet/bridge
        - docker start -a -i bridgec
        - bridge build
